InvoiceNo: Invoice number. Nominal. A 6-digit integral number uniquely assigned to each transaction. If this code starts with the letter 'c', it indicates a cancellation. 


StockCode: Product (item) code. Nominal. A 5-digit integral number uniquely assigned to each distinct product. 


Description: Product (item) name. Nominal. 


Quantity: The quantities of each product (item) per transaction. Numeric.	


InvoiceDate: Invice date and time. Numeric. The day and time when a transaction was generated. 


UnitPrice: Unit price. Numeric. Product price per unit in sterling (Â£). 


CustomerID: Customer number. Nominal. A 5-digit integral number uniquely assigned to each customer. 


Country: Country name. Nominal. The name of the country where a customer resides.

In [2]:
import pandas as pd

In [3]:
file_path = "../data/online_retail_II.xlsx"

df = pd.read_excel(file_path)

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [3]:
df.shape

(525461, 8)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

In [5]:
df.describe()

            Quantity                 InvoiceDate          Price    Customer ID
count  525461.000000                      525461  525461.000000  417534.000000
mean       10.337667  2010-06-28 11:37:36.845018       4.688834   15360.645478
min     -9600.000000         2009-12-01 07:45:00  -53594.360000   12346.000000
25%         1.000000         2010-03-21 12:20:00       1.250000   13983.000000
50%         3.000000         2010-07-06 09:51:00       2.100000   15311.000000
75%        10.000000         2010-10-15 12:45:00       4.210000   16799.000000
max     19152.000000         2010-12-09 20:01:00   25111.090000   18287.000000
std       107.424110                         NaN     146.126914    1680.811316

In [6]:
df.describe(include="object")

C:\Users\nifeo\AppData\Local\Temp\ipykernel_29260\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

        Invoice StockCode                         Description         Country
count    525461    525461                              522533          525461
unique    28816      4632                                4681              40
top      537434    85123A  WHITE HANGING HEART T-LIGHT HOLDER  United Kingdom
freq        675      3516                                3549          485852

In [18]:
df[df["Quantity"] < 0].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,2009-12-01 10:33:00,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom

In [23]:
df[(df["Quantity"] < 0)].describe(include="object")

C:\Users\nifeo\AppData\Local\Temp\ipykernel_29260\758881630.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df[(df["Quantity"] < 0)].describe(include="object")

        Invoice StockCode Description         Country
count     12326     12326       10499           12326
unique     6712      3117        2351              31
top     C524235         M      Manual  United Kingdom
freq         45       293         293           10914

In [16]:
df[df["Price"] < 0].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom

In [26]:
df[df["Price"] == 0].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom

In [13]:
df[df["Quantity"] > 1000].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
7302,490018,21981,PACK OF 12 WOODLAND TISSUES,4320,2009-12-03 12:31:00,0.25,17940.0,United Kingdom
7303,490018,21967,PACK OF 12 SKULL TISSUES,5184,2009-12-03 12:31:00,0.25,17940.0,United Kingdom
7304,490018,21984,PACK OF 12 PINK PAISLEY TISSUES,4008,2009-12-03 12:31:00,0.25,17940.0,United Kingdom
7305,490018,21980,PACK OF 12 RED SPOTTY TISSUES,4008,2009-12-03 12:31:00,0.25,17940.0,United Kingdom
17384,490758,72008,NaN,3000,2009-12-08 09:38:00,0.00,NaN,United Kingdom
22100,491133,16014,SMALL CHINESE STYLE SCISSOR,1500,2009-12-09 16:17:00,0.32,13848.0,United Kingdom
23689,491212,20668,DISCO BALL CHRISTMAS DECORATION,1002,2009-12-10 14:28:00,0.10,14062.0,United Kingdom
24815,491440,72756,FAIRY CAKE CANDLES,1080,2009-12-11 10:31:00,1.25,16029.0,United Kingdom
33391,492185,16014,SMALL CHINESE STYLE SCISSOR,3000,2009-12-15 15:48:00,0.32,16308.0,United Kingdom
43522,493108,47503F,NaN,2300,2009-12-22 11:23:00,0.00,NaN,United Kingdom

In [31]:
# Number of cancellations

df["Invoice"].str.startswith("C").value_counts()

Invoice
True     10206
False        3
Name: count, dtype: int64

In [33]:
# Number of negative quantities
(df["Quantity"] < 0).sum()

np.int64(12326)

In [ ]:
# Number of zero price records
(df["Price"] == 0).sum()

np.int64(3687)

In [35]:
# Number of negative price records
(df["Price"] < 0).sum()

np.int64(3)

In [36]:
# Unusual invoice prefix
df["Invoice"].str[0].value_counts(dropna=False)

Invoice
NaN    515252
C       10206
A           3
Name: count, dtype: int64

In [38]:
# Investigate the zero price records
df[df["Price"] == 0]["Description"].value_counts(dropna=False).head(20)

Description
NaN                                    2928
?                                        45
damages                                  39
damaged                                  38
missing                                  24
OWL DOORSTOP                              8
checked                                   8
POLYESTER FILLER PAD 45x45cm              7
PICNIC BASKET WICKER LARGE                7
FLAG OF ST GEORGE CAR FLAG                6
dotcom                                    6
HEART OF WICKER SMALL                     6
AIRLINE BAG VINTAGE WORLD CHAMPION        6
given away                                6
smashed                                   5
POLYESTER FILLER PAD 40x40cm              5
SMALL POPCORN HOLDER                      5
WATERING CAN BLUE ELEPHANT                5
ENAMEL FIRE BUCKET CREAM                  5
ENAMEL WASH BOWL CREAM                    5
Name: count, dtype: int64

In [39]:
df[df["Price"] == 0]["StockCode"].value_counts().head(20)

StockCode
46000M    12
84016     11
22423     11
79321     10
84990     10
22469     10
22950     10
22197      9
22139      9
21116      8
84795D     8
22501      8
22734      8
46000S     7
21768      7
22429      7
22502      7
22470      7
71477      6
37446      6
Name: count, dtype: int64

In [40]:
df[df["Price"] == 0][["Invoice", "StockCode", "Description", "Quantity", "Customer ID"]].head(20)

     Invoice StockCode          Description  Quantity  Customer ID
263   489464     21733         85123a mixed       -96          NaN
283   489463     71477                short      -240          NaN
284   489467    85123A          21733 mixed      -192          NaN
470   489521     21646                  NaN       -50          NaN
3114  489655     20683                  NaN       -44          NaN
3161  489659     21350                  NaN       230          NaN
3162  489660     35956                 lost     -1043          NaN
3168  489663    35605A              damages      -117          NaN
3731  489781     84292                  NaN        17          NaN
4296  489806     18010                  NaN      -770          NaN
4538  489820     21133      invcd as 84879?      -720          NaN
4566  489821    85049G                  NaN      -240          NaN
4674  489825     22076   6 RIBBONS EMPIRE          12      16126.0
5904  489861       DOT       DOTCOM POSTAGE         1          NaN
6378  489882    35751C                  NaN        12          NaN
6555  489898    79323G                  NaN       954          NaN
6556  489899   79323GR         sold as gold      -954          NaN
6576  489901     21098                  NaN      -200          NaN
6581  489903     21166                  NaN        48          NaN
6781  489998     48185  DOOR MAT FAIRY CAKE         2      15658.0

In [41]:
df.duplicated().sum()

np.int64(6865)

In [42]:
df[df.duplicated(keep=False)].sort_values(
    ["Invoice", "StockCode"]
).head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom

Investigate missing values

In [50]:
df["Customer ID"].isna().value_counts()

Customer ID
False    417534
True     107927
Name: count, dtype: int64

In [51]:
df.groupby(df["Customer ID"].isna())["Quantity"].agg(
    ["count", "sum", "mean"]
)

              count      sum       mean
Customer ID
False        417534  5327239  12.758815
True         107927   104802   0.971045

In [52]:
df.groupby(df["Customer ID"].isna())["Price"].agg(
    ["count", "mean", "median"]
)

              count      mean  median
Customer ID
False        417534  3.887547    1.95
True         107927  7.788750    3.36

In [53]:
df[df["Customer ID"].isna()]["Quantity"].apply(
    lambda x: "positive" if x > 0 else "negative" if x < 0 else "zero"
).value_counts()

Quantity
positive    105440
negative      2487
Name: count, dtype: int64

In [54]:
pd.crosstab(
    df["Customer ID"].isna(),
    df["Quantity"] > 0,
    normalize="index"
)

Quantity        False     True
Customer ID
False        0.023565  0.976435
True         0.023043  0.976957

In [55]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [4]:
from src.pipeline import transform_data

df_transformed = transform_data(df)

df_transformed.head()

,invoice,stock_code,description,quantity,invoice_date,price,customer_id,country,is_cancellation,line_total
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,False,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,False,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,False,30.0

In [5]:
df_transformed.dtypes

invoice                    string
stock_code                 string
description                object
quantity                    int64
invoice_date       datetime64[us]
price                     float64
customer_id                string
country                       str
is_cancellation           boolean
line_total                float64
dtype: object